#-------------------------------------
#-- Site
#-------------------------------------

#-- Output paths (relative to nwayo folder) and output url
output:
  konstan: ../test/fixtures/build
  build:   ../test/fixtures/build
  url:     /build


#-- Scripts
scripts:
  options:
    minify: false
    babel:
      - '> 1%'
      - 'last 2 versions'
      - 'not ie < 11'

  allowBabel:
    - bower_components/foundation-sites
    - bower_components/nwayo-toolbox



#-- Styles
styles:
  options:
    minify: false
    sourcemaps: false
    autoprefixer:
      - '> 1%'
      - 'last 2 versions'
      - 'not ie < 11'
