# http://eslint.org/docs/rules/

# Extends
# n/a


# Parser Options
# n/a


# Environments
env:
  browser: false
  jquery: false
  node: true


# Globals
globals: []


# Plugins
# n/a


# Settings
# n/a


# Rules
rules:

  # Possible Errors
  # n/a


  # Best Practices
  # n/a


  # Strict Mode
  strict: [error, global]

  # Variables
  # n/a


  # Node.js and CommonJS
  callback-return: [error]
  global-require: [error]
  handle-callback-err: [error]
  no-mixed-requires: [error]
  no-new-require: [error]
  no-path-concat: [error]
  no-process-env: [error]
  no-process-exit: [error]
  no-restricted-modules: [off]
  no-sync: [off]


  # Stylistic Issues
  # n/a


  # ECMAScript 6
  no-restricted-imports:
    - error
    - assert
    - buffer
    - child_process
    - cluster
    - crypto
    - dgram
    - dns
    - domain
    - events
    - freelist
    - fs
    - http
    - https
    - module
    - net
    - os
    - path
    - punycode
    - querystring
    - readline
    - repl
    - smalloc
    - stream
    - string_decoder
    - sys
    - timers
    - tls
    - tracing
    - tty
    - url
    - util
    - vm
    - zlib
