# http://eslint.org/docs/rules/

# Parser Options
root: true
parser: espree
parserOptions:
  ecmaVersion: 6
  sourceType: script
  ecmaFeatures:
    globalReturn: false
    impliedStrict: false
    jsx: false
    experimentalObjectRestSpread: true

# Plugins
#plugins:

# Extends
#extends: eslint:all

# Rules
rules:

  # Possible Errors
  no-cond-assign: [error, always]
  #no-console:
  #no-constant-condition:
  #no-control-regex:
  no-debugger: [error]
  #no-dupe-args:
  #no-dupe-keys:
  #no-duplicate-case:
  #no-empty-character-class:
  no-empty: [error, {allowEmptyCatch: false}]
  #no-ex-assign:
  #no-extra-boolean-cast:
  no-extra-parens: [error, all]
  #no-extra-semi:
  #no-func-assign:
  #no-inner-declarations:
  #no-invalid-regexp:
  no-irregular-whitespace: [error]
  #no-obj-calls:
  #no-prototype-builtins:
  #no-regex-spaces:
  no-sparse-arrays: [error]
  #no-template-curly-in-string:
  #no-unexpected-multiline:
  #no-unreachable:
  #no-unsafe-finally:
  #no-unsafe-negation:
  #use-isnan:
  #valid-jsdoc:
  valid-typeof: [error]


  # Best Practices
  #accessor-pairs:
  #array-callback-return:
  block-scoped-var: [error]
  complexity: [off]
  #consistent-return:
  curly: [error, all]
  #default-case:
  #dot-location:
  dot-notation: [error, {allowKeywords: true}]
  eqeqeq: [error, always]
  guard-for-in: [error]
  #no-alert:
  no-caller: [error]
  #no-case-declarations:
  #no-div-regex:
  #no-else-return:
  #no-empty-function:
  #no-empty-pattern:
  no-eq-null: [error]
  no-eval: [error]
  no-extend-native: [error]
  #no-extra-bind:
  #no-extra-label:
  #no-fallthrough:
  #no-floating-decimal:
  #no-global-assign:
  #no-implicit-coercion:
  #no-implicit-globals:
  #no-implied-eval:
  no-invalid-this: [off]
  no-iterator: [error]
  #no-labels:
  #no-lone-blocks:
  no-loop-func: [error]
  #no-magic-numbers:
  #no-multi-spaces:
  no-multi-str: [error]
  no-new-func: [error]
  no-new-wrappers: [error]
  no-new: [error]
  #no-octal-escape:
  #no-octal:
  #no-param-reassign:
  no-proto: [error]
  #no-redeclare:
  #no-return-assign:
  no-script-url: [error]
  #no-self-assign:
  #no-self-compare:
  no-sequences: [error]
  #no-throw-literal:
  #no-unmodified-loop-condition:
  no-unused-expressions: [error]
  #no-unused-labels:
  #no-useless-call:
  #no-useless-concat:
  #no-useless-escape:
  #no-void:
  #no-warning-comments:
  no-with: [error]
  #radix:
  #vars-on-top:
  wrap-iife: [error, inside]
  #yoda:


  # Strict Mode
  strict: [error, function]


  # Variables
  #init-declarations:
  #no-catch-shadow:
  #no-delete-var:
  #no-label-var:
  no-restricted-globals: [error, window]
  #no-shadow-restricted-names:
  no-shadow: [error, {builtinGlobals: false, hoist: all}]
  #no-undef-init:
  no-undef: [error]
  #no-undefined:
  no-unused-vars: [error]
  no-use-before-define: [error]


  # Node.js and CommonJS
  #callback-return:
  #global-require:
  #handle-callback-err:
  #no-mixed-requires:
  #no-new-require:
  #no-path-concat:
  #no-process-env:
  #no-process-exit:
  #no-restricted-modules:
  #no-sync:


  # Stylistic Issues
  #array-bracket-spacing:
  #block-spacing:
  #brace-style:
  camelcase: [error, {properties: always}]
  comma-dangle: [error, never] #always-multiline
  #comma-spacing:
  comma-style: [error, last]
  #computed-property-spacing:
  #consistent-this:
  #eol-last:
  #func-call-spacing:
  #func-names:
  #func-style:
  #id-blacklist:
  #id-length:
  #id-match:
  indent: [error, tab, {SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1, MemberExpression: 1}]
  #jsx-quotes:
  #key-spacing:
  #keyword-spacing:
  linebreak-style: [error, unix]
  #lines-around-comment:
  max-depth: [off]
  max-len: [off]
  #max-lines:
  #max-nested-callbacks:
  max-params: [off]
  #max-statements-per-line:
  max-statements: [off]
  #multiline-ternary:
  new-cap: [error, {newIsCap: true, capIsNew: true, properties: false}]
  #new-parens:
  #newline-after-var:
  #newline-before-return:
  #newline-per-chained-call:
  #no-array-constructor:
  no-bitwise: [error]
  #no-continue:
  #no-inline-comments:
  #no-lonely-if:
  #no-mixed-operators:
  #no-mixed-spaces-and-tabs:
  #no-multiple-empty-lines:
  #no-negated-condition:
  #no-nested-ternary:
  #no-new-object:
  no-plusplus: [off]
  #no-restricted-syntax:
  #no-tabs:
  #no-ternary:
  #no-trailing-spaces:
  #no-underscore-dangle:
  #no-unneeded-ternary:
  #no-whitespace-before-property:
  #object-curly-newline:
  #object-curly-spacing:
  #object-property-newline:
  #one-var-declaration-per-line:
  #one-var:
  #operator-assignment:
  #operator-linebreak:
  #padded-blocks:
  #quote-props:
  quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
  #require-jsdoc:
  #semi-spacing:
  semi: [error, always]
  #sort-keys:
  #sort-vars:
  #space-before-blocks:
  #space-before-function-paren:
  #space-in-parens:
  #space-infix-ops:
  #space-unary-ops:
  #spaced-comment:
  #unicode-bom:
  #wrap-regex:


  # ECMAScript 6
  #arrow-body-style:
  #arrow-parens:
  #arrow-spacing:
  #constructor-super:
  #generator-star-spacing:
  #no-class-assign:
  #no-confusing-arrow:
  #no-const-assign:
  #no-dupe-class-members:
  #no-duplicate-imports:
  #no-new-symbol:
  #no-restricted-imports:
  #no-this-before-super:
  #no-useless-computed-key:
  #no-useless-constructor:
  #no-useless-rename:
  no-var: [error]
  #object-shorthand:
  #prefer-arrow-callback:
  #prefer-const:
  #prefer-reflect:
  #prefer-rest-params:
  #prefer-spread:
  #prefer-template:
  require-yield: [error]
  #rest-spread-spacing:
  #sort-imports:
  #template-curly-spacing:
  #yield-star-spacing:


# Environments
env:
  browser: true
  es6: true
  jquery: true
  #node: false
  #commonjs: false
  #shared-node-browser: false
  #worker: false
  #amd: false
  #mocha: false
  #jasmine: false
  #jest: false
  #phantomjs: false
  #protractor: false
  #qunit: false
  #prototypejs: false
  #shelljs: false
  #meteor: false
  #mongo: false
  #applescript: false
  #nashorn: false
  #serviceworker: false
  #atomtest: false
  #embertest: false
  #webextensions: false
  #greasemonkey: false


# Globals
globals:
  global: false
  $Global: false
  Modernizr: false
  Foundation: false
  _: false
  PubSub: false
  Cookies: false
  kafe: false
  google: false
  konstan: false
  app: false
  __: false
