# http://eslint.org/docs/rules/

# Parser Options
root: true
parser: espree
parserOptions:
  ecmaVersion: 6
  sourceType: script
  ecmaFeatures:
    globalReturn: false
    impliedStrict: false
    jsx: false
    experimentalObjectRestSpread: true

# Plugins
#plugins:

# Extends
#extends: eslint:all

# Rules
rules:

  # Possible Errors
  no-cond-assign: [error, always]
  no-console: [warn]
  no-constant-condition: [error]
  no-control-regex: [error]
  no-debugger: [error]
  no-dupe-args: [error]
  no-dupe-keys: [error]
  no-duplicate-case: [error]
  no-empty-character-class: [error]
  no-empty: [error, {allowEmptyCatch: false}]
  no-ex-assign: [error]
  no-extra-boolean-cast: [error]
  no-extra-parens: [error, all]
  no-extra-semi: [error]
  no-func-assign: [error]
  no-inner-declarations: [error, both]
  no-invalid-regexp: [error]
  no-irregular-whitespace: [error]
  no-obj-calls: [error]
  no-prototype-builtins: [error]
  no-regex-spaces: [error]
  no-sparse-arrays: [error]
  no-template-curly-in-string: [error]
  no-unexpected-multiline: [error]
  no-unreachable: [error]
  no-unsafe-finally: [error]
  no-unsafe-negation: [error]
  use-isnan: [error]
  valid-jsdoc: [off]  #TODO: check
  valid-typeof: [error]


  # Best Practices
  accessor-pairs: [error, {setWithoutGet: true, getWithoutSet: true}]
  array-callback-return: [error]
  block-scoped-var: [error]
  complexity: [off]
  consistent-return: [error]
  curly: [error, all]
  default-case: [error]
  dot-location: [error, property]
  dot-notation: [error, {allowKeywords: true}]
  eqeqeq: [error, always]
  guard-for-in: [error]
  no-alert: [warn]
  no-caller: [error]
  no-case-declarations: [error]
  no-div-regex: [error]
  no-else-return: [error]
  no-empty-function: [error]
  no-empty-pattern: [error]
  no-eq-null: [error]
  no-eval: [error]
  no-extend-native: [error]
  no-extra-bind: [error]
  no-extra-label: [error]
  no-fallthrough: [error]
  no-floating-decimal: [error]
  no-global-assign: [error]
  no-implicit-coercion: [error]
  no-implicit-globals: [error]
  no-implied-eval: [error]
  no-invalid-this: [off]
  no-iterator: [error]
  no-labels: [error]
  no-lone-blocks: [error]
  no-loop-func: [error]
  no-magic-numbers: [off]
  no-multi-spaces: [off]
  no-multi-str: [error]
  no-new-func: [error]
  no-new-wrappers: [error]
  no-new: [error]
  no-octal-escape: [error]
  no-octal: [error]
  no-param-reassign: [error]
  no-proto: [error]
  no-redeclare: [error, {builtinGlobals: true}]
  no-return-assign: [error, always]
  no-script-url: [error]
  no-self-assign: [error, {props: true}]
  no-self-compare: [error]
  no-sequences: [error]
  no-throw-literal: [error]
  no-unmodified-loop-condition: [error]
  no-unused-expressions: [error]
  no-unused-labels: [error]
  no-useless-call: [error]
  no-useless-concat: [error]
  no-useless-escape: [error]
  no-void: [error]
  no-warning-comments: [warn, {location: anywhere}]
  no-with: [error]
  radix: [error, always]
  vars-on-top: [error]
  wrap-iife: [error, inside]
  yoda: [error, never]


  # Strict Mode
  strict: [error, function]


  # Variables
  #init-declarations:
  #no-catch-shadow:
  #no-delete-var:
  #no-label-var:
  no-restricted-globals: [error, window]
  #no-shadow-restricted-names:
  no-shadow: [error, {builtinGlobals: false, hoist: all}]
  #no-undef-init:
  no-undef: [error]
  #no-undefined:
  no-unused-vars: [error]
  no-use-before-define: [error]


  # Node.js and CommonJS
  #callback-return:
  #global-require:
  #handle-callback-err:
  #no-mixed-requires:
  #no-new-require:
  #no-path-concat:
  #no-process-env:
  #no-process-exit:
  #no-restricted-modules:
  #no-sync:


  # Stylistic Issues
  #array-bracket-spacing:
  #block-spacing:
  #brace-style:
  camelcase: [error, {properties: always}]
  comma-dangle: [error, never] #always-multiline
  #comma-spacing:
  comma-style: [error, last]
  #computed-property-spacing:
  #consistent-this:
  #eol-last:
  #func-call-spacing:
  #func-names:
  #func-style:
  #id-blacklist:
  #id-length:
  #id-match:
  indent: [error, tab, {SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1, MemberExpression: 1}]
  #jsx-quotes:
  #key-spacing:
  #keyword-spacing:
  linebreak-style: [error, unix]
  #lines-around-comment:
  max-depth: [off]
  max-len: [off]
  #max-lines:
  #max-nested-callbacks:
  max-params: [off]
  #max-statements-per-line:
  max-statements: [off]
  #multiline-ternary:
  new-cap: [error, {newIsCap: true, capIsNew: true, properties: false}]
  #new-parens:
  #newline-after-var:
  #newline-before-return:
  #newline-per-chained-call:
  #no-array-constructor:
  no-bitwise: [error]
  #no-continue:
  #no-inline-comments:
  #no-lonely-if:
  #no-mixed-operators:
  #no-mixed-spaces-and-tabs:
  #no-multiple-empty-lines:
  #no-negated-condition:
  #no-nested-ternary:
  #no-new-object:
  no-plusplus: [off]
  #no-restricted-syntax:
  #no-tabs:
  #no-ternary:
  #no-trailing-spaces:
  #no-underscore-dangle:
  #no-unneeded-ternary:
  #no-whitespace-before-property:
  #object-curly-newline:
  #object-curly-spacing:
  #object-property-newline:
  #one-var-declaration-per-line:
  #one-var:
  #operator-assignment:
  #operator-linebreak:
  #padded-blocks:
  #quote-props:
  quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
  #require-jsdoc:
  #semi-spacing:
  semi: [error, always]
  #sort-keys:
  #sort-vars:
  #space-before-blocks:
  #space-before-function-paren:
  #space-in-parens:
  #space-infix-ops:
  #space-unary-ops:
  #spaced-comment:
  #unicode-bom:
  #wrap-regex:


  # ECMAScript 6
  #arrow-body-style:
  #arrow-parens:
  #arrow-spacing:
  #constructor-super:
  #generator-star-spacing:
  #no-class-assign:
  #no-confusing-arrow:
  #no-const-assign:
  #no-dupe-class-members:
  #no-duplicate-imports:
  #no-new-symbol:
  #no-restricted-imports:
  #no-this-before-super:
  #no-useless-computed-key:
  #no-useless-constructor:
  #no-useless-rename:
  no-var: [error]
  #object-shorthand:
  #prefer-arrow-callback:
  #prefer-const:
  #prefer-reflect:
  #prefer-rest-params:
  #prefer-spread:
  #prefer-template:
  require-yield: [error]
  #rest-spread-spacing:
  #sort-imports:
  #template-curly-spacing:
  #yield-star-spacing:


# Environments
env:
  browser: true
  es6: true
  jquery: true
  #node: false
  #commonjs: false
  #shared-node-browser: false
  #worker: false
  #amd: false
  #mocha: false
  #jasmine: false
  #jest: false
  #phantomjs: false
  #protractor: false
  #qunit: false
  #prototypejs: false
  #shelljs: false
  #meteor: false
  #mongo: false
  #applescript: false
  #nashorn: false
  #serviceworker: false
  #atomtest: false
  #embertest: false
  #webextensions: false
  #greasemonkey: false


# Globals
globals:
  global: false
  $Global: false
  Modernizr: false
  Foundation: false
  _: false
  PubSub: false
  Cookies: false
  kafe: false
  google: false
  konstan: false
  app: false
  __: false
