# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/compass/README.md

exclude: 'bower_components/**/*.scss,components/theme-*/**/*.scss,components/vendor-*/**/*.scss'

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    # max_elements: null

  BorderZero:
    enabled: true
    convention: zero

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: false
    # allowed: null
    style: silent

  DebugStatement:
    enabled: false

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true
    #ignore_consecutive: false

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab
    width: 1

  LeadingZero:
    enabled: true
    style: exclude_zero

  MergeableSelector:
    enabled: true
    force_nesting: true
    # whitelist: null

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: hyphenated_lowercase
    # convention_explanation:
    # {type}_convention:
    # {type}_convention_explanation:

  NestingDepth:
    enabled: false
    # max_depth: null
    # ignore_parent_selectors: null

  PlaceholderInExtend:
    enabled: false

  PrivateNamingConvention:
    enabled: true

  PropertyCount:
    enabled: false
    # include_nested: null
    # max_properties: null

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order:
      - content
      - quotes

      - position
      - top
      - right
      - bottom
      - left
      - z-index

      - display
      - float
      - clear
      - overflow
      - overflow-x
      - overflow-y
      - visibility
      - opacity
      - list-style
      - vertical-align

      - box-sizing
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - outline
      - box-shadow

      - background
      - background-color
      - background-image
      - background-repeat
      - background-position
      - background-size

      - color
      - font
      - font-family
      - font-size
      - font-weight
      - font-smoothing
      - font-style
      - text-align
      - text-indent
      - text-transform
      - text-decoration
      - text-rendering
      - text-shadow
      - text-overflow
      - line-height
      - word-spacing
      - letter-spacing
      - white-space

      - caption-side
      - table-layout
      - border-collapse
      - border-spacing
      - empty-cells
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width

      - transform
      - transition
      - cursor


  PropertySpelling:
    enabled: true
    # extra_properties: null
    # disabled_properties: null

  PropertyUnits:
    enabled: false
    # global: null
    # properties: null

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: false
    # max_depth: null

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
    # convention_explanation: null
    # ignored_names: null
    # ignored_types: null
    # {type}_convention: null
    # {type}_convention_explanation: null

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: true
    style: at_least_one_space

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: at_least_one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true
    style: space

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    # properties: null

  VendorPrefixes:
    enabled: true
    identifier_list: base
    # additional_identifiers: null
    # excluded_identifiers: null

  ZeroUnit:
    enabled: true

  Compass::PropertyWithMixin:
    enabled: false
    # ignore: null
