pipelines:
  default:
    - parallel:
        - step:
            name: Test latest Node.js version
            image: 'node:latest'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - npm test
        - step:
            name: Test Node.js 16
            image: 'node:16'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - npm test
        - step:
            name: Test Node.js 14
            image: 'node:14'
            caches:
              - node
            script:
              - npm ci --unsafe-perm
              - npm test
