pipelines:
  default:
    - parallel:
        - step:
            name: Test latest Node.js version
            image: 'node:latest'
            caches:
              - node
            script:
              - npm install --unsafe-perm
              - npm test
        - step:
            name: Test latest stable Node.js version
            image: 'node:12'
            caches:
              - node
            script:
              - npm install --unsafe-perm
              - npm test
