# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:

  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: false

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: false
#    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

#  HexLength:
#    enabled: true
#    style: short
#
#  HexNotation:
#    enabled: true
#    style: lowercase
#
#  HexValidation:
#    enabled: true
#
#  IdWithExtraneousSelector:
#    enabled: true
#
#  Indentation:
#    enabled: true
#    character: tab
#    width: 1
#
#  LeadingZero:
#    enabled: true
#
#  MergeableSelector:
#    enabled: true
#     force_nesting
#
#  NameFormat:
#    enabled: false
#
#  PlaceholderInExtend:
#    enabled: true
#
#  PropertySortOrder:
#    enabled: true
#    ignore_unspecified: true
#    order:
#      - display
##      - ipsum
#
#  PropertySpelling:
#    enabled: true
##    extra_properties:
##      - lorem
##      - ipsum
#
#  SelectorDepth:
#    enabled: false
#
#  Shorthand:
#    enabled: true
#
#  SingleLinePerProperty:
#    enabled: false
#
#  SingleLinePerSelector:
#    enabled: false
#
#  SpaceAfterComma:
#    enabled: true
#
#  SpaceAfterPropertyColon:
#    enabled: true
#    style: no_space
#
#  SpaceAfterPropertyName:
#    enabled: true
#
#  SpaceBeforeBrace:
#    enabled: true
#    allow_single_line_padding: true
#
#  SpaceBetweenParens:
#    enabled: true
#    spaces: 0
#
#  StringQuotes:
#    enabled: true
#    style: single_quotes
#
#  TrailingSemicolon:
#    enabled: true
#
#  UnnecessaryMantissa:
#    enabled: true
#
#  UnnecessaryParentReference:
#    enabled: true
#
#  UrlFormat:
#    enabled: false
#
#  UrlQuotes:
#    enabled: true
#
#  ZeroUnit:
#    enabled: true
#
## https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/compass/README.md
#  Compass::PropertyWithMixin:
#    enabled: false
#