module.exports = function(grunt) {

	// Project configuration.
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		
		requirejs: {
			compile: {
				options: {
					baseUrl: './',
					name: 'js/core',
					out: '../assets/builds/require-test.js',
					paths: {
						'jquery':     'libs/plugins/jquery/jquery',
						'underscore': 'libs/plugins/underscore',
						'modernizr':  'libs/plugins/modernizr'
					},
					 optimize: "none",
					 preserveLicenseComments: false,
					 skipModuleInsertion: true,
					 findNestedDependencies: true
				}
			}
		},

		// js
		// jshint: {
		// 	default_js: {
		// 		src: ['js/**/*.js', '!libs/plugins/**/**.js']
		// 	}
		// },
		// uglify: {
		// 	options: {
		// 		banner: '/* generated by grunt on <%= grunt.template.today("yyyy-mm-dd HH:MM:ss") %> */\n'
		// 	},
		// 	default_js: {
		// 		src: ['js/plugins/jquery.js', 'js/plugins/underscore.js', 'js/plugins/modernizr.js', 'js/core.js', 'js/pages.js'],
		// 		dest: '../assets/builds/core.js'
		// 	}
		// },
		
		
		// less
		less: {
			default_less: {
				options: {
					paths: 'less',
					yuicompress: true,
					strictImports: true
				},
				files: {
					'../assets/builds/core.css': 'less/loader.less'
				}
			}
		},
		concat: {
			default_less: {
				files: [{
					src: ['less/libs/unsemantic-grid-responsive.css', '../assets/builds/core.css'],
					dest: '../assets/builds/core.css'
				}]
			}
		},
		
		
		// watcher
		watch: {
//			js: {
//				files: ['Gruntfile.js', 'package.json', 'js/**/*.js', 'libs/**/*.js'],
//				tasks: 'default_js'
//			},
			less: {
				files: ['Gruntfile.js', 'package.json', 'less/**/*.less'],
				tasks: 'default_less'
			}
		}
		
		
	});

	// Load the plugin that provides the "uglify" task.
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-less');
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-contrib-requirejs');
	grunt.loadNpmTasks('grunt-contrib-watch');

	// Default task(s).
	//grunt.registerTask('default_js',   ['jshint','uglify']);
	grunt.registerTask('default_less', ['less','concat']);
	grunt.registerTask('default', ['requirejs']);

};