#debug  = require 'gulp-debug'
gulp   = require 'gulp'

util = require './_util'
path = util.path

konstan_filename = 'konstan.json'



#-- Convert constants to JSON
gulp.task 'local_constants', ->
	merge = require 'merge-stream'

	streams = []
	for bname, bundle of util.bundles

		data = {
			GENERATION: "Generated by nwayo #{util.pkg.nwayo.version} for #{util.pkg.name}:#{bname}"
			nwayo:      util.pkg.nwayo.version
			project:    util.pkg.name
			bundle:     bname
			konstan:    util.parse_konstan 'local', bundle.output.url
		}

		streams.push(
			util.vinyl_stream konstan_filename, JSON.stringify(data, null, 2)
				.pipe gulp.dest bundle.output.konstan
		)

	return merge.apply null, streams



#-- Rebuild
gulp.task 'local', (cb) ->
	del         = require 'del'
	runsequence = require 'run-sequence'

	list = []
	list.push "#{bundle.output.konstan}/#{konstan_filename}" for bname, bundle of util.bundles

	del list, force:true, ->
		runsequence ['local_constants'], cb
