extends: "@valtech-commerce/eslint-config/react"

parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
    - "@babel/preset-react"
  ecmaFeatures:
      jsx: true

settings:
  react:
    version: "17.0.2"
