#-------------------------------------
#-- Site
#-------------------------------------

#-- Output paths (relative to nwayo folder) and output url
output:
  konstan: ../src/web/build
  build:   ../src/web/build
  url:     /build



#-- Assets
assets:
  components:
    - common
    - form
    - site



#-- Scripts
scripts:
  options:
    minify: false

  allowBabel:
    - bower_components/foundation-sites

  collections:
    dependencies:
      - components/nwayo/scripts/exclusion-starter
      - ~konstan
      - bower_components/jquery/dist/jquery
      - ~lodash
      - ~modernizr
      - bower_components/pubsub-js/src/pubsub
      - bower_components/fastclick/lib/fastclick
      - bower_components/what-input/dist/what-input
      - components/vendor-foundation/scripts/vendor-foundation
      - components/nwayo/scripts/dependencies-starter

    common:
      - components/nwayo/scripts/collection-starter
      - components/common/scripts/common
      - components/form/scripts/form

    site:
      - components/nwayo/scripts/collection-starter
      - components/site/scripts/site

    SAMPLE:
      - components/nwayo/scripts/collection-starter
      - components/SAMPLE/scripts/SAMPLE



#-- Styles
styles:
  options:
    minify: false
    autoprefixer:
      - '> 1%'
      - 'last 2 versions'
      - 'and_chr >= 2.3'
      - 'ie >= 9'

  collections:
    main:
      - components/site/styles/config
      - components/vendor-foundation/styles/vendor-foundation
      - components/common/styles/common
      - components/site/styles/site
      - components/form/styles/form

    SAMPLE:
      - components/SAMPLE/styles/config
      - components/SAMPLE/styles/SAMPLE

    editor:
      - components/site/styles/config
      - components/vendor-foundation/styles/vendor-foundation
      - components/site/styles/fonts
      - components/site/styles/layout
      - components/cms/styles/editor
