#-------------------------------------
#-- site
#-------------------------------------

#-- output paths (relative to nwayo folder) and output url
output:
  konstan: __konstan-path__/site-out
  build:   __build-path__/site-out
  url:     /nwayo/__build-path__/site-out



#-- assets
assets:
  components:
    - form
    - site



#-- scripts
scripts:
  options:
    minify: true

  collections:
    dependencies:
      - ~konstan
      - bower_components/jquery/dist/jquery
      - bower_components/lodash/lodash
      - ~modernizr
      - bower_components/pubsub-js/src/pubsub
      - components/nwayo/scripts/dependencies-starter

    main:
      - components/nwayo/scripts/collection-starter
      - components/common/scripts/common
      - components/site/scripts/site
      - components/form/scripts/form



#-- styles
styles:
  options:
    minify: true
    autoprefixer:
      - '> 1%'
      - 'last 2 versions'
      - 'ie >= 9'
      - 'Firefox ESR'
      - 'Opera 12.1'

  collections:
    main:
      - components/common/styles/common
      - components/site/styles/site
      - components/form/styles/form

    editor:
      - components/common/styles/common
      - components/cms/styles/editor

