#-------------------------------------
#-- Site
#-------------------------------------

#-- Output paths (relative to nwayo folder) and output url
output:
  konstan: ../src/web/build
  build:   ../src/web/build
  url:     /build



#-- Assets
assets:
  components:
    - form
    - site



#-- Scripts
scripts:
  options:
    minify: false

  collections:
    dependencies:
      - ~konstan
      - bower_components/jquery/dist/jquery
      - ~lodash
      - ~modernizr
      - bower_components/pubsub-js/src/pubsub
      - bower_components/fastclick/lib/fastclick
      - components/vendor-bootstrap/scripts/vendor-bootstrap
      - components/nwayo/scripts/dependencies-starter

    main:
      - components/nwayo/scripts/collection-starter
      - components/common/scripts/common
      - components/form/scripts/form
      - components/site/scripts/site



#-- Styles
styles:
  options:
    minify: false
    autoprefixer:
      - '> 1%'
      - 'last 2 versions'
      - 'Android 2.3'
      - 'Android >= 4'
      - 'Chrome >= 20'
      - 'Firefox >= 24'
      - 'Explorer >= 8'
      - 'iOS >= 6'
      - 'Opera >= 12'
      - 'Safari >= 6'

  collections:
    main:
      - components/common/styles/common
      - components/vendor-bootstrap/styles/vendor-bootstrap
      - components/site/styles/site
      - components/form/styles/form

    editor:
      - components/common/styles/common
      - components/vendor-bootstrap/styles/vendor-bootstrap
      - components/cms/styles/editor
