extends:
  - "./node_modules/@absolunet/nwayo-workflow/config/eslint.cjs"
  - "./node_modules/@absolunet/nwayo-workflow/config/eslint-no-prettier.cjs"

# Environments
#env:


# Globals
#globals:
  #spConfig: readonly
  #Translator: readonly
  #Validation: readonly


# Rules
#rules:
