extends: '@absolunet/browser'


parserOptions:
  sourceType: module

# Environments
#env:


# Globals
#globals:
  #spConfig: readonly
  #Translator: readonly
  #Validation: readonly


# Rules
rules:

  no-console: [warn]
  no-debugger: [warn]

  no-alert: [warn]
  no-warning-comments: [warn, { location: anywhere }]
