extends:
  - '@absolunet/nwayo'
  - './node_modules/@absolunet/nwayo-workflow/ressources/eslint-config-pre-prettier.cjs'

# Environments
#env:


# Globals
#globals:
  #spConfig: readonly
  #Translator: readonly
  #Validation: readonly


# Rules
#rules:
