#-------------------------------------
#-- site
#-------------------------------------

#-- output paths (relative to nwayo folder) and output url
output:
  konstan: __konstan-output-to-change/siteout
  build:   __build-output-to-change/siteout
  url:     /nwayo/__build-output-to-change/siteout



#-- assets
assets:
  components:
    - form
    - site



#-- scripts
scripts:
  options:
    minify: false

  collections:
    dependencies:
      - konstan
      - bower_components/jquery/dist/jquery
      - bower_components/lodash/lodash
      - bower_components/underscore.string/dist/underscore.string
      - bower_components/modernizr/modernizr
      - bower_components/pubsub-js/src/pubsub
      - bower_components/kafe/dist/kafe
      - components/nwayo/scripts/dependencies-starter

    main:
      - components/nwayo/scripts/collection-starter
      - components/common/scripts/common
      - components/site/scripts/site
      - components/form/scripts/form



#-- styles
styles:
  options:
    minify: false
    autoprefixer:
      - '> 1%'
      - 'last 2 versions'
      - 'ie >= 9'
      - 'Firefox ESR'
      - 'Opera 12.1'

  collections:
    main:
      - components/common/styles/common
      - components/site/styles/site
      - components/form/styles/form

    editor:
      - components/common/styles/common
      - components/cms/styles/editor

