#-------------------------------------
#-- Site
#-------------------------------------

#-- Output paths (relative to nwayo folder) and output url
output:
  konstan: ../../../test/fixtures/build
  build:   ../../../test/fixtures/build
  url:     /build


#-- Assets
assets:
  components:
    - common
    - form
    - site


#-- Scripts
scripts:
  options:
    minify: false
    babel:              #  http://browserl.ist/?q=%3E+.25%25
      - '> .25%'

  allowBabel:
    - vendor/node_modules/foundation-sites
    - vendor/node_modules/nwayo-toolbox
    - vendor/node_modules/pinki



#-- Styles
styles:
  options:
    minify: false
    sourcemaps: false
    autoprefixer:       #  http://browserl.ist/?q=%3E+.25%25
      - '> .25%'
