#-------------------------------------
#-- Site
#-------------------------------------

#-- Output paths (relative to nwayo folder) and output url
output:
  konstan: ../../../test/fixtures/build
  build:   ../../../test/fixtures/build
  url:     /build


#-- Assets
assets:
  components:
    - common
    - form
    - site


#-- Scripts
scripts:
  options:
    minify: false
    babel:              #  https://browserl.ist/?q=%3E+.25%25%2C+not+dead
      - '> .25%'
      - 'not dead'

  allowBabel:
    - vendor/node_modules/foundation-sites
    - vendor/node_modules/@absolunet/nwayo-toolbox
    - vendor/node_modules/@absolunet/pinki



#-- Styles
styles:
  options:
    minify: false
    sourcemaps: false
    autoprefixer:       #  https://browserl.ist/?q=%3E+.25%25%2C+not+dead
      - '> .25%'
      - 'not dead'
